import { Platform }  from 'react-native';
export const URL_BASE="http://ilifenetwork.com/api/web/v1";
export const URL_USER_LOGIN="/customers/login";
export const URL_USER_OTP="/customers/send_otp";
export const URL_USER_SIGNUP='/customers/signup';
export const SEND_MECHANIC_OTP='/customers/send_mechanic_otp';
export const URL_USER_INFO='/app/api/userinfo';
export const GET_VENDOR ='/customers/get_vendor';
export const GET_BOOKING ='/bookings/booking';
export const GET_BOOKINGLIST ='/bookings/get_booking';
export const POST_RATING ='/customers/rating';
export const GET_FUTURE_BOOKINGLIST ='/bookings/get_vendor_booking';
export const BOOKING_UPDATE='/bookings/booking_update';
export const GET_USER_DATA='/customers/get_user'
export const UPDATE_PROFILE='/customers/update_profile';
export const URL_TIMESHEET_SUBMIT='/app/api/submit';
export const URL_CREATE_TIMESHEETS='/app/api/create_timesheet';
export const WEBCALL_SUCCESSFUL_FLAG=100;
export const URL_USER_LOGOUT="/app/api/logout";
